name: Futurerestore

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: 0
    - name: Setup MSYS
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        release: false
        update: false
    - name: Windows Build
      run: |
        uname -a
        pwd
        ls -lath
